language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
  - "pypy"
before_install:
  # Update pip before install to check if this pass travis ci test
  - pip install -U pip
# command to install dependencies
install:
  - pip install .
# command to run tests
script: nosetests
